### ISSUE TITLE
Colab updated limitations

### ISSUE THREAD

**Issue by 0x09AF** [danielcshn/wpa-colab#2]
Google has cracked down (pardon the pun) on password cracking - now they explicitly state in their usage policy that cracking (amongst other restrictions) is not allowed, and my account has been restricted access to Colab (but not other G products).

When you download and compile `hashcat` - they do give you a warning about running possibly restricted code and they may ban you for that, which I disregarded, so it is only fair.

Feel free to move to discussions, because it's not really an issue

**Comment by danielcshn** [comment]
Hi, thank you for the notice. A warning has been added to the readme.
